-- ============================================================================
-- DAILY SWEEPS TABLE
-- ============================================================================
-- Stores comprehensive daily operations reports generated by code-bot's
-- daily-sweep cron job. Discord gets a short summary; the full report,
-- structured metrics, and action items live here for the admin dashboard.
-- Date: 2026-03-02
-- ============================================================================

CREATE TABLE IF NOT EXISTS daily_sweeps (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sweep_date DATE NOT NULL UNIQUE,
  summary TEXT,                        -- Short Discord summary
  report TEXT,                         -- Full markdown report
  metrics JSONB DEFAULT '{}',          -- Structured metrics for cards/trends
  action_items JSONB DEFAULT '[]',     -- [{priority, title, description, category}]
  health_score TEXT DEFAULT 'unknown', -- healthy | warning | critical
  cost DECIMAL(10,4),
  turns INTEGER,
  duration_seconds INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Row Level Security
ALTER TABLE daily_sweeps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "auth read" ON daily_sweeps
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "service insert" ON daily_sweeps
  FOR INSERT TO service_role WITH CHECK (true);

-- Index for date-ordered queries
CREATE INDEX idx_daily_sweeps_date ON daily_sweeps (sweep_date DESC);

-- Grants
GRANT SELECT ON daily_sweeps TO authenticated;
GRANT ALL ON daily_sweeps TO service_role;

-- Table/column comments
COMMENT ON TABLE daily_sweeps IS 'Daily operations sweep reports from code-bot cron job';
COMMENT ON COLUMN daily_sweeps.summary IS 'Short summary posted to Discord';
COMMENT ON COLUMN daily_sweeps.report IS 'Full markdown report rendered in admin dashboard';
COMMENT ON COLUMN daily_sweeps.metrics IS 'Structured metrics JSON for dashboard cards and trends';
COMMENT ON COLUMN daily_sweeps.action_items IS 'Array of action items: [{priority, title, description, category}]';
COMMENT ON COLUMN daily_sweeps.health_score IS 'Overall health: healthy | warning | critical';
